// Generates the M3 token layer. Reference tones come from one seed colour;
// system roles are named decisions on top of them. Nothing downstream should
// ever write a literal colour.
import {
  themeFromSourceColor, argbFromHex, hexFromArgb, TonalPalette,
} from '@material/material-color-utilities';
import { readFileSync, existsSync } from 'node:fs';
import { dirname, join } from 'node:path';

// Identity lives in orrery.config.json; the system below is the foundation.
const ROOT = join(dirname(new URL(import.meta.url).pathname), '..');
const CONFIG_PATH = process.env.ORRERY_CONFIG || join(ROOT, 'orrery.config.json');
const CFG = existsSync(CONFIG_PATH) ? JSON.parse(readFileSync(CONFIG_PATH, 'utf8')) : {};

const SEED = CFG.seed || '#00707F';
const SUCCESS_SEED = CFG.successSeed || '#1F6F4A';
const WARN_SEED = CFG.warnSeed || '#8A5A00';
const SANS = CFG.sansStack || '"IBM Plex Sans", ui-sans-serif, system-ui, sans-serif';
const MONO = CFG.monoStack || '"IBM Plex Mono", ui-monospace, Menlo, Consolas, monospace';

const kebab = s => s.replace(/([a-z0-9])([A-Z])/g, '$1-$2').toLowerCase();

// M3's surface-container family is not in the scheme object; it is defined as
// fixed tones of the neutral palette, so derive it rather than inventing greys.
const SURFACES = {
  light: { surface:98, surfaceDim:87, surfaceBright:98, surfaceContainerLowest:100,
           surfaceContainerLow:96, surfaceContainer:94, surfaceContainerHigh:92,
           surfaceContainerHighest:90 },
  dark:  { surface:6, surfaceDim:6, surfaceBright:24, surfaceContainerLowest:4,
           surfaceContainerLow:10, surfaceContainer:12, surfaceContainerHigh:17,
           surfaceContainerHighest:22 },
};
const EXTRA = {            // tone pairs for a custom role, per M3 convention
  light: { base:40, on:100, container:90, onContainer:10 },
  dark:  { base:80, on:20,  container:30, onContainer:90 },
};

function roles(mode){
  const theme = themeFromSourceColor(argbFromHex(SEED));
  const scheme = theme.schemes[mode].toJSON();
  const out = {};
  for (const [k, v] of Object.entries(scheme)) out[kebab(k)] = hexFromArgb(v);

  const n = theme.palettes.neutral, nv = theme.palettes.neutralVariant;
  for (const [k, tone] of Object.entries(SURFACES[mode])) out[kebab(k)] = hexFromArgb(n.tone(tone));
  out['outline-variant'] = hexFromArgb(nv.tone(mode === 'light' ? 80 : 30));
  out['surface-tint'] = out['primary'];

  for (const [name, seed] of [['success', SUCCESS_SEED], ['warn', WARN_SEED]]) {
    const p = TonalPalette.fromInt(argbFromHex(seed)), t = EXTRA[mode];
    out[name] = hexFromArgb(p.tone(t.base));
    out['on-' + name] = hexFromArgb(p.tone(t.on));
    out[name + '-container'] = hexFromArgb(p.tone(t.container));
    out['on-' + name + '-container'] = hexFromArgb(p.tone(t.onContainer));
  }
  return out;
}

const block = mode => Object.entries(roles(mode))
  .map(([k, v]) => `  --md-sys-color-${k}: ${v};`).join('\n');

// M3 "fixed" roles: colours that must not flip with the theme. A terminal block
// is dark in both schemes, so text on it always needs the dark-scheme variants.
function fixedBlock(){
  const theme = themeFromSourceColor(argbFromHex(SEED));
  const dark = theme.schemes.dark.toJSON();
  const warn = TonalPalette.fromInt(argbFromHex(WARN_SEED));
  const ok = TonalPalette.fromInt(argbFromHex(SUCCESS_SEED));
  return [
    `  --md-sys-color-error-fixed: ${hexFromArgb(dark.error)};`,
    `  --md-sys-color-primary-fixed: ${hexFromArgb(dark.primary)};`,
    `  --md-sys-color-warn-fixed: ${hexFromArgb(warn.tone(80))};`,
    `  --md-sys-color-success-fixed: ${hexFromArgb(ok.tone(80))};`,
  ].join('\n');
}

export function tokensCss(){
  return `/* generated by build/tokens.mjs from seed ${SEED} — do not edit by hand */
:root {
${block('light')}
}
@media (prefers-color-scheme: dark) { :root:not([data-theme="light"]) {
${block('dark')}
}}
:root[data-theme="dark"] {
${block('dark')}
}

:root {
${fixedBlock()}

  /* shape */
  --shape-xs: 4px;  --shape-sm: 8px;  --shape-md: 12px;
  --shape-lg: 16px; --shape-xl: 28px; --shape-full: 999px;

  /* elevation, M3 levels */
  --elev-0: none;
  --elev-1: 0 1px 2px 0 rgb(0 0 0 / .30), 0 1px 3px 1px rgb(0 0 0 / .15);
  --elev-2: 0 1px 2px 0 rgb(0 0 0 / .30), 0 2px 6px 2px rgb(0 0 0 / .15);
  --elev-3: 0 1px 3px 0 rgb(0 0 0 / .30), 0 4px 8px 3px rgb(0 0 0 / .15);
  --elev-4: 0 2px 3px 0 rgb(0 0 0 / .30), 0 6px 10px 4px rgb(0 0 0 / .15);

  /* state layer opacities */
  --state-hover: .08; --state-focus: .10; --state-press: .10; --state-drag: .16;
  --state-disabled-content: .38; --state-disabled-container: .12;

  /* motion */
  --dur-short: 150ms; --dur-med: 250ms; --dur-long: 420ms;
  --ease-standard: cubic-bezier(.2, 0, 0, 1);
  --ease-emphasized: cubic-bezier(.2, 0, 0, 1);
  --ease-decel: cubic-bezier(.05, .7, .1, 1);
  --ease-accel: cubic-bezier(.3, 0, .8, .15);

  /* type */
  --font-sans: ${SANS};
  --font-mono: ${MONO};
}
`;
}
